# Generated by Django 4.0.6 on 2022-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('room_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True)),
                ('projector', models.IntegerField(blank=True)),
                ('ac', models.IntegerField(blank=True)),
                ('computer', models.IntegerField(blank=True)),
                ('desks', models.IntegerField(blank=True)),
                ('whiteboard', models.IntegerField(blank=True)),
                ('count', models.IntegerField(blank=True)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
